### ISSUE TITLE
LRUCache.has(key: TKey) returning true event if expired

### ISSUE THREAD

**Issue by BenDevelopment** [rob893/typescript-lru-cache#2]
The method has(key: TKey) returns if the lookupTable has the given key without taking on account if the cache corresponding to the key is exipred or not.

**Comment by rob893** [comment]
Good catch! Will fix soon.

**Comment by rob893** [comment]
Fix is in this PR https://github.com/rob893/typescript-lru-cache/pull/3

Will publish new major version soon as this is technically a breaking change.

**Comment by rob893** [comment]
Fixed in new release: https://github.com/rob893/typescript-lru-cache/releases/tag/v2.0.0
